# Term0 Week2 授業前課題3
## コーディング課題：内積

## 1. 内積を手計算
以下のような行列A,Bを考える。
$$A =
\begin{pmatrix}
-1 & 2 & 3 \\
4 & -5 & 6 \\
7 & 8 & -9 \\
\end{pmatrix}, 
B=
\begin{pmatrix}
0 & 2 & 1 \\
0 & 2 & -8 \\
2 & 9 & -1 \\
\end{pmatrix}$$
行列の内積$A*B$を手計算で解く。

$$A*B=
\begin{pmatrix}
(-1)*0+2*0+3*2 & (-1)*2+2*2+3*9 & (-1)*1+2*(-8)+3*(-1) \\
4*0+(-5)*0+6*2 & 4*2+(-5)*2+6*9 & 4*1+(-5)*(-8)+6*(-1) \\
7*0+8*0+(-9)*2 & 7*2+8*2+(-9)*9 & 7*1+8*(-8)+(-9)*(-1) \\
\end{pmatrix}
=
\begin{pmatrix}
6 & 29 & -20 \\
12 & 52 & 38 \\
-18 & -51 & -48 \\
\end{pmatrix}$$

## 2. 1次元配列の内積をfor文で計算
行列Aの(0,0)の要素と行列Bの(0,0)の要素を掛け合わせる  
行列Aの(0,1)の要素と行列Bの(1,0)の要素を掛け合わせる  
行列Aの(0,2)の要素と行列Bの(2,0)の要素を掛け合わせる  
それらの値を全て足し合わせる  
というフローを得て、ようやく一つ目の要素が求まる。

次の要素を計算するには、行列のindexを増やし、上の過程を再度繰り返して行けばよい。配列のindexを指定し、  
行列Aの(0,0)の要素と行列Bの(0,1)の要素を掛け合わせる  
行列Aの(0,1)の要素と行列Bの(1,1)の要素を掛け合わせる  
行列Aの(0,2)の要素と行列Bの(2,1)の要素を掛け合わせる  
それらの値を全て足し合わせる  
のフローをfor文を使って計算する。

In [24]:
import numpy as np
A=np.array([[-1,2,3],[4,-5,6],[7,8,-9]])
B=np.array([[0,2,1],[0,2,-8],[2,9,-1]])

# (0, 0)要素を計算
index00=0
for i, j in zip(A[0, :], B[:, 0]):
    index00+=i * j
print("(0, 0)要素：", index00)

# (0, 1)要素を計算
index01=0
for i, j in zip(A[0, :], B[:, 1]):
    index01+=i * j
print("(0, 1)要素：", index01)

(0, 0)要素： 6
(0, 1)要素： 29


## 3. 多次元配列の内積をfor文で計算
2.ではA*Bの(0,0)だけ計算するコードを実装したが、全要素を求めるにはどうしたらよいか。

行列A*Bの(0,1)を求めるには

行列Aのインデックスは固定（0行目を選択したまま）で、行列Bのインデックスを0列目から1列目に指定しなおせばよい。

行列Aの(0,0)の要素と行列Bの(0,1)の要素を掛け合わせる  
行列Aの(0,1)の要素と行列Bの(1,1)の要素を掛け合わせる  
行列Aの(0,2)の要素と行列Bの(2,1)の要素を掛け合わせる  
1、2、3で求めた値を足し合わせる  
とすればA*Bの(0,1)の要素が求まる。  

このように同じ計算を順次インデックスを増やして行けば、全要素の計算ができる。
以下では、for文を使って行列A、Bの積を計算する。

In [25]:
Answer_for = np.zeros((3,3))
for r in range(A.shape[0]):
    for c in range(B.shape[1]):
        for i, j in zip(A[r,:], B[:,c]):
            Answer_for[r,c] += i*j
print("for文での行列計算結果：\n", Answer_for)

for文での行列計算結果：
 [[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


## 4. 内積をnp.dotで計算
np.dot(A,B)を計算して、【課題3】と同じになることを試す。

In [26]:
Answer_np = np.dot(A,B)
print("numpy.dotでの行列計算結果：\n", Answer_np)
print("for文計算結果とnumpy.dot計算結果は一致しているか：", "一致" if np.unique(Answer_for==Answer_np)==[1,] else "不一致")

numpy.dotでの行列計算結果：
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
for文計算結果とnumpy.dot計算結果は一致しているか： 一致


## 5. 内積ができないときはどうするか
以下のような例を考える。
$$A =
\begin{pmatrix}
-1 & 2 & 3 \\
4 & -5 & 6 \\
\end{pmatrix}, 
B=
\begin{pmatrix}
-9 & 8 & 7 \\
6 & -5 & 4 \\
\end{pmatrix}$$

行列A\*Bを計算しようとすると、エラーが出て計算できない理由は何か。  
そして、行列A、Bのどちらかにある操作をするとエラーが出ずに計算できる。  
自分である操作を施し、内積を計算する。

In [27]:
A = np.array([[-1,2,3],[4,-5,6]])
B = np.array([[-9,8,7],[6,-5,4]])
# この場合、行列Aの列数と行列Bの行数が一致していないので、A*Bではエラーが出る。
# AまたはBのどちらかを転値して行列計算する。

# A転置の場合
print("A転置の場合：\n", A.T.dot(B))

# B転置の場合
print("B転置の場合：\n", A.dot(B.T))

A転置の場合：
 [[ 33 -28   9]
 [-48  41  -6]
 [  9  -6  45]]
B転置の場合：
 [[ 46  -4]
 [-34  73]]
